
title: Badger's Corner
url: 
author: bitbrain
email: miguel-gonzalez@gmx.de
description: > # this means to ignore newlines until "show_exerpts:"
  Join me, will you? On a programming journey!
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/jbraunsmajr
      icon: github-square
      color: yellow
  
  avatar_source: local
  avatar_path: /public/avatar.webp

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - horace_readme.md
  - jekyll.thor
  - netlify.toml
  - run
  - Changelog.md
  - questions.md
  - "*.cs"
  - "*.csproj"
  - /bin
  - /obj
  - /.idea
  - Commands
include:
  - _redirects